// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyConfigProfile(arg1) {
  return window['go']['app']['App']['ApplyConfigProfile'](arg1);
}

export function DeleteClaudeConfig() {
  return window['go']['app']['App']['DeleteClaudeConfig']();
}

export function DeleteConfigProfile(arg1) {
  return window['go']['app']['App']['DeleteConfigProfile'](arg1);
}

export function GetClaudeConfigPath() {
  return window['go']['app']['App']['GetClaudeConfigPath']();
}

export function GetProfilesDir() {
  return window['go']['app']['App']['GetProfilesDir']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function LoadClaudeConfig() {
  return window['go']['app']['App']['LoadClaudeConfig']();
}

export function LoadConfigProfiles() {
  return window['go']['app']['App']['LoadConfigProfiles']();
}

export function SaveClaudeConfig(arg1, arg2) {
  return window['go']['app']['App']['SaveClaudeConfig'](arg1, arg2);
}

export function SaveConfigProfile(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SaveConfigProfile'](arg1, arg2, arg3, arg4);
}
