// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyConfigProfile(arg1:string):Promise<main.ConfigResponse>;

export function DeleteConfigProfile(arg1:string):Promise<main.ConfigResponse>;

export function GetClaudeConfigPath():Promise<string>;

export function GetProfilesDir():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LoadClaudeConfig():Promise<main.ConfigResponse>;

export function LoadConfigProfiles():Promise<main.ConfigResponse>;

export function SaveClaudeConfig(arg1:string,arg2:string):Promise<main.ConfigResponse>;

export function SaveConfigProfile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.ConfigResponse>;
